### ISSUE TITLE
Images, Summary and Feature List is same for all works

### ISSUE THREAD

**Issue by ajayaadhav10** [MdMostaFizurRahaman/getprofile#8]
The Portfolio you made with Next JS is amazing!! although in works--> [id].tsx file is redirecting to the same Summary and Feature List content, but I want to change all my work Summary and Feature list to different content as it varies upon different works, how can I do that, as I'm new to Next Js. I can see that Dynamic Routes is used for all the id's.

**Comment by mostafizurhimself** [comment]
First pull the latest code & run 

```
yarn install
```
Now, you will find a `works.ts` file under `src/data` directory. 

<img width="219" alt="image" src="https://user-images.githubusercontent.com/42089253/194790757-a2de7b45-913c-413e-81e8-e59866f26463.png">

In this file, all the work related static contents are listed. From here you can change the contents as your needs. Or you can integrate your own api to get dynamic contents.

**Comment by ajayaadhav10** [comment]
Thanks, for making the works and blog content dynamic!!
